Repository matheusa1/cafe-books-front, pull requests merged in 2023-09, with the labels that each got.

#30 Autores into main
  public/mock/images/arakifofo.png
  public/mock/images/clarise.avif
  public/mock/images/mauriso.jpg
  public/mock/images/steven.jpg
  src/app/(home)/page.tsx
  src/components/initialPageSections/Authors/index.tsx
  src/components/molecules/AuthorsItem/index.tsx
  src/components/molecules/AuthorsItem/types.ts
  src/components/organism/AuthorsBar/index.tsx
  src/mock/authorsData.ts
Labels: FRONT, SCREEN SECTION, Enchantment

#37 Separamos para voce into main
  public/mock/images/boxSherlock.png
  src/app/(home)/page.tsx
  src/components/atoms/Button/index.tsx
  src/components/atoms/SecondaryTitle/index.tsx
  src/components/atoms/SecondaryTitle/types.ts
  src/components/initialPageSections/ForYou/index.tsx
  src/components/molecules/ForYouBottomSlider/index.tsx
  src/components/molecules/ForYouBottomSliderItem/index.tsx
  src/components/organism/ForYouCard/index.tsx
  tailwind.config.ts
Labels: FRONT, SCREEN SECTION

#41 Integrar tela de cadastro
  src/app/auth/layout.tsx
  src/app/auth/sign-up/page.tsx
  src/app/auth/sign-up/types.ts
  src/components/atoms/Form/Input/index.tsx
  src/components/atoms/Form/SelectForm/index.tsx
  src/components/atoms/Form/SelectForm/types.ts
  src/components/atoms/Form/TextArea/index.tsx
  src/components/atoms/Input/index.tsx
  src/components/molecules/AdminBooksCreateUpdateBooks/index.tsx
  src/services/api.ts
Labels: FRONT, Enchantment, Integração

#45 Desenvolver integração com cloudinary
  package.json
  pnpm-lock.yaml
  src/app/admin/hot/page.tsx
  src/components/atoms/Form/InputFile/index.tsx
  src/components/atoms/Form/InputFile/types.ts
  src/components/atoms/Form/index.tsx
  src/components/atoms/InputFile/index.tsx
  src/components/atoms/InputFile/types.ts
  src/components/molecules/AdminBooksCreateUpdateBooks/index.tsx
  src/components/molecules/AdminBooksCreateUpdateBooks/types.ts
  src/services/api.ts
Labels: FRONT, SCREEN, Enchantment, Integração

#47 Tela de pesquisa
  src/app/(home)/book-info/[id]/page.tsx
  src/app/(home)/explore/layout.tsx
  src/app/(home)/explore/page.tsx
  src/components/atoms/BackButton/index.tsx
  src/components/atoms/Select/types.ts
  src/components/atoms/ViewMoreButton/index.tsx
  src/components/initialPageSections/HeadboardItems/index.tsx
  src/components/molecules/ExploreFilterItem/index.tsx
  src/components/molecules/ExploreFilterItem/types.ts
  src/components/molecules/HeadboardItem/index.tsx
  src/components/molecules/HeadboardItem/types.ts
  src/components/organism/ExploreFilter/index.tsx
  src/components/organism/ExploreFilter/types.ts
  src/components/organism/ExploreHeader/index.tsx
  src/components/organism/ExploreHeader/types.ts
  src/components/organism/MainContentExplore/index.tsx
  src/components/organism/MainContentExplore/types.ts
Labels: FRONT, SCREEN, Enchantment, Integração

#48 refactor: :art: Better structure
  src/app/(home)/book-info/[id]/page.tsx
Labels: FRONT, SCREEN, Layout

#54 refactor: :ambulance: now images are fixed
  package.json
  pnpm-lock.yaml
  src/components/molecules/AdminBooksCreateUpdateBooks/index.tsx
  src/components/molecules/AdminBooksCreateUpdateBooks/types.ts
Labels: FRONT, SCREEN, BUG

#52 Ajuste de cores
  .env.local.exemple
  src/app/auth/layout.tsx
  src/app/auth/sign-up/page.tsx
  src/app/globals.css
  src/components/atoms/Button/index.tsx
  src/components/atoms/Form/Input/index.tsx
  src/components/atoms/Form/SelectForm/index.tsx
  src/components/atoms/Input/index.tsx
  src/components/atoms/Select/index.tsx
  src/components/atoms/Select/types.ts
  src/components/atoms/ViewMoreButton/index.tsx
  src/components/molecules/AuthorsItem/index.tsx
  src/components/molecules/CategoriesItem/index.tsx
  src/components/organism/ExploreHeader/index.tsx
  src/services/api.ts
  tailwind.config.ts
Labels: FRONT, Layout

#55 Integrar categorias tela inicial
  .vscode/settings.json
  src/app/(home)/explore/page.tsx
  src/assets/images/notFoundImage.png
  src/components/atoms/ImageWithFallback/index.tsx
  src/components/initialPageSections/Categories/index.tsx
  src/components/molecules/CategoriesItem/index.tsx
  src/components/molecules/CategoriesItem/types.ts
  src/components/organism/CategoriesSwiper/index.tsx
  src/components/organism/CategoriesSwiper/types.ts
Labels: BUG, SCREEN SECTION, Enchantment, Integração

#56 Homolog
  .vscode/settings.json
  src/app/(home)/explore/page.tsx
  src/assets/images/notFoundImage.png
  src/components/atoms/ImageWithFallback/index.tsx
  src/components/initialPageSections/Categories/index.tsx
  src/components/molecules/CategoriesItem/index.tsx
  src/components/molecules/CategoriesItem/types.ts
  src/components/organism/CategoriesSwiper/index.tsx
  src/components/organism/CategoriesSwiper/types.ts
Labels: FRONT, SCREEN SECTION, Enchantment, Integração

#59 feat: :sparkles: Filtro trabalha junto com Home
  next.config.js
  src/app/(home)/explore/page.tsx
  src/components/organism/ExploreFilter/index.tsx
Labels: FRONT, SCREEN, Enchantment
